[tool.poetry]
name = "merge_gis"
version = "0.1.0"
description = ""
authors = ["Timothy Holmes <tim.a.holmes@gmail.com>"]
packages = [
    {include = "merge_gis", from = "src"},
    {include = "trace_gis", from = "src"}
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
